// US Ski Resorts data for GoWindow
// Generated from ski resort coordinates database

// Timezone mapping by state
const STATE_TIMEZONES = {
  'Alabama': 'America/Chicago',
  'Alaska': 'America/Anchorage',
  'Arizona': 'America/Phoenix',
  'California': 'America/Los_Angeles',
  'Colorado': 'America/Denver',
  'Connecticut': 'America/New_York',
  'Idaho': 'America/Boise',
  'Illinois': 'America/Chicago',
  'Indiana': 'America/Indiana/Indianapolis',
  'Iowa': 'America/Chicago',
  'Maine': 'America/New_York',
  'Maryland': 'America/New_York',
  'Massachusetts': 'America/New_York',
  'Michigan': 'America/Detroit',
  'Minnesota': 'America/Chicago',
  'Missouri': 'America/Chicago',
  'Montana': 'America/Denver',
  'Nevada': 'America/Los_Angeles',
  'New Hampshire': 'America/New_York',
  'New Jersey': 'America/New_York',
  'New Mexico': 'America/Denver',
  'New York': 'America/New_York',
  'North Carolina': 'America/New_York',
  'North Dakota': 'America/Chicago',
  'Ohio': 'America/New_York',
  'Oregon': 'America/Los_Angeles',
  'Pennsylvania': 'America/New_York',
  'Rhode Island': 'America/New_York',
  'South Dakota': 'America/Chicago',
  'Tennessee': 'America/New_York',
  'Utah': 'America/Denver',
  'Vermont': 'America/New_York',
  'Virginia': 'America/New_York',
  'Washington': 'America/Los_Angeles',
  'West Virginia': 'America/New_York',
  'Wisconsin': 'America/Chicago',
  'Wyoming': 'America/Denver'
};

// State abbreviations for display
const STATE_ABBREV = {
  'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'California': 'CA',
  'Colorado': 'CO', 'Connecticut': 'CT', 'Idaho': 'ID', 'Illinois': 'IL',
  'Indiana': 'IN', 'Iowa': 'IA', 'Maine': 'ME', 'Maryland': 'MD',
  'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Missouri': 'MO',
  'Montana': 'MT', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ',
  'New Mexico': 'NM', 'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND',
  'Ohio': 'OH', 'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI',
  'South Dakota': 'SD', 'Tennessee': 'TN', 'Utah': 'UT', 'Vermont': 'VT',
  'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV', 'Wisconsin': 'WI',
  'Wyoming': 'WY'
};

export const SKI_RESORTS = [
  { name: "Cloudmont", city: "Mentone", state: "AL", lat: 34.5075, lon: -85.6394, timezone: "America/Chicago" },
  { name: "Alyeska", city: "Girdwood", state: "AK", lat: 60.9698, lon: -149.0983, timezone: "America/Anchorage" },
  { name: "Arctic Valley", city: "Anchorage", state: "AK", lat: 61.246, lon: -149.5347, timezone: "America/Anchorage" },
  { name: "Birch Hill", city: "Fairbanks", state: "AK", lat: 64.87, lon: -147.68, timezone: "America/Anchorage" },
  { name: "Eaglecrest", city: "Juneau", state: "AK", lat: 58.3036, lon: -134.5131, timezone: "America/Anchorage" },
  { name: "Hillberg", city: "Anchorage", state: "AK", lat: 61.155, lon: -149.795, timezone: "America/Anchorage" },
  { name: "Hilltop", city: "Anchorage", state: "AK", lat: 61.1389, lon: -149.7861, timezone: "America/Anchorage" },
  { name: "Homer Rope Tow", city: "Homer", state: "AK", lat: 59.715, lon: -151.47, timezone: "America/Anchorage" },
  { name: "Moose Mountain", city: "Palmer", state: "AK", lat: 61.4453, lon: -149.0267, timezone: "America/Anchorage" },
  { name: "Mount Eyak", city: "Cordova", state: "AK", lat: 60.5421, lon: -145.7536, timezone: "America/Anchorage" },
  { name: "Skeetawk", city: "Hatcher Pass", state: "AK", lat: 61.6108, lon: -149.3197, timezone: "America/Anchorage" },
  { name: "Ski Land", city: "Fairbanks", state: "AK", lat: 64.9, lon: -147.44, timezone: "America/Anchorage" },
  { name: "Arizona Snowbowl", city: "Flagstaff", state: "AZ", lat: 35.3315, lon: -111.7107, timezone: "America/Phoenix" },
  { name: "Mt. Lemmon Ski Valley", city: "Tucson", state: "AZ", lat: 32.442, lon: -110.726, timezone: "America/Phoenix" },
  { name: "Sunrise Park", city: "Greer", state: "AZ", lat: 33.973, lon: -109.5457, timezone: "America/Phoenix" },
  { name: "Alta Sierra", city: "Wofford Heights", state: "CA", lat: 35.75, lon: -118.52, timezone: "America/Los_Angeles" },
  { name: "Badger Pass", city: "Yosemite", state: "CA", lat: 37.6625, lon: -119.6631, timezone: "America/Los_Angeles" },
  { name: "Bear Mountain (Big Bear)", city: "Big Bear Lake", state: "CA", lat: 34.2286, lon: -116.8592, timezone: "America/Los_Angeles" },
  { name: "Bear Valley", city: "Bear Valley", state: "CA", lat: 38.4647, lon: -120.0419, timezone: "America/Los_Angeles" },
  { name: "Boreal", city: "Truckee", state: "CA", lat: 39.3322, lon: -120.3489, timezone: "America/Los_Angeles" },
  { name: "Cedar Pass", city: "Weed", state: "CA", lat: 41.52, lon: -122.64, timezone: "America/Los_Angeles" },
  { name: "China Peak", city: "Lakeshore", state: "CA", lat: 37.2347, lon: -119.1572, timezone: "America/Los_Angeles" },
  { name: "Coppervale", city: "Mineral", state: "CA", lat: 40.28, lon: -121.07, timezone: "America/Los_Angeles" },
  { name: "Dodge Ridge", city: "Pinecrest", state: "CA", lat: 38.1903, lon: -119.9556, timezone: "America/Los_Angeles" },
  { name: "Donner Ski Ranch", city: "Norden", state: "CA", lat: 39.3181, lon: -120.3306, timezone: "America/Los_Angeles" },
  { name: "Granlibakken", city: "Tahoe City", state: "CA", lat: 39.1531, lon: -120.1714, timezone: "America/Los_Angeles" },
  { name: "Heavenly", city: "South Lake Tahoe", state: "CA", lat: 38.9353, lon: -119.94, timezone: "America/Los_Angeles" },
  { name: "Homewood", city: "Homewood", state: "CA", lat: 39.0839, lon: -120.1617, timezone: "America/Los_Angeles" },
  { name: "June Mountain", city: "June Lake", state: "CA", lat: 37.7672, lon: -119.0903, timezone: "America/Los_Angeles" },
  { name: "Kingvale", city: "Soda Springs", state: "CA", lat: 39.32, lon: -120.38, timezone: "America/Los_Angeles" },
  { name: "Kirkwood", city: "Kirkwood", state: "CA", lat: 38.685, lon: -120.0656, timezone: "America/Los_Angeles" },
  { name: "Mammoth", city: "Mammoth Lakes", state: "CA", lat: 37.6308, lon: -119.0328, timezone: "America/Los_Angeles" },
  { name: "Mountain High: West", city: "Wrightwood", state: "CA", lat: 34.3747, lon: -117.6906, timezone: "America/Los_Angeles" },
  { name: "Mountain High: East", city: "Wrightwood", state: "CA", lat: 34.3786, lon: -117.6767, timezone: "America/Los_Angeles" },
  { name: "Mt. Baldy", city: "Mt Baldy", state: "CA", lat: 34.2528, lon: -117.6469, timezone: "America/Los_Angeles" },
  { name: "Mt. Shasta", city: "Mt Shasta", state: "CA", lat: 41.3517, lon: -122.2036, timezone: "America/Los_Angeles" },
  { name: "Northstar", city: "Truckee", state: "CA", lat: 39.2745, lon: -120.121, timezone: "America/Los_Angeles" },
  { name: "Palisades Tahoe: Olympic", city: "Olympic Valley", state: "CA", lat: 39.1969, lon: -120.2358, timezone: "America/Los_Angeles" },
  { name: "Sierra-at-Tahoe", city: "Twin Bridges", state: "CA", lat: 38.8003, lon: -120.0803, timezone: "America/Los_Angeles" },
  { name: "Snow Summit (Big Bear)", city: "Big Bear Lake", state: "CA", lat: 34.2375, lon: -116.8892, timezone: "America/Los_Angeles" },
  { name: "Snow Valley", city: "Running Springs", state: "CA", lat: 34.225, lon: -117.0375, timezone: "America/Los_Angeles" },
  { name: "Soda Springs", city: "Soda Springs", state: "CA", lat: 39.3194, lon: -120.3781, timezone: "America/Los_Angeles" },
  { name: "Sugar Bowl", city: "Norden", state: "CA", lat: 39.3047, lon: -120.3356, timezone: "America/Los_Angeles" },
  { name: "Tahoe Donner", city: "Truckee", state: "CA", lat: 39.35, lon: -120.27, timezone: "America/Los_Angeles" },
  { name: "Arapahoe Basin", city: "Dillon", state: "CO", lat: 39.6425, lon: -105.8719, timezone: "America/Denver" },
  { name: "Aspen Highlands", city: "Aspen", state: "CO", lat: 39.1775, lon: -106.8556, timezone: "America/Denver" },
  { name: "Aspen Mountain", city: "Aspen", state: "CO", lat: 39.1869, lon: -106.8186, timezone: "America/Denver" },
  { name: "Beaver Creek", city: "Avon", state: "CO", lat: 39.6042, lon: -106.5164, timezone: "America/Denver" },
  { name: "Breckenridge", city: "Breckenridge", state: "CO", lat: 39.4817, lon: -106.0667, timezone: "America/Denver" },
  { name: "Buttermilk", city: "Aspen", state: "CO", lat: 39.2067, lon: -106.8619, timezone: "America/Denver" },
  { name: "Chapman", city: "Steamboat Springs", state: "CO", lat: 40.74, lon: -106.81, timezone: "America/Denver" },
  { name: "Copper Mountain", city: "Frisco", state: "CO", lat: 39.5022, lon: -106.1497, timezone: "America/Denver" },
  { name: "Cranor Hill", city: "Gunnison", state: "CO", lat: 38.53, lon: -106.97, timezone: "America/Denver" },
  { name: "Crested Butte", city: "Crested Butte", state: "CO", lat: 38.8986, lon: -106.9653, timezone: "America/Denver" },
  { name: "Cuchara", city: "Cuchara", state: "CO", lat: 37.31, lon: -105.1, timezone: "America/Denver" },
  { name: "Echo Mountain", city: "Idaho Springs", state: "CO", lat: 39.6847, lon: -105.5169, timezone: "America/Denver" },
  { name: "Eldora", city: "Nederland", state: "CO", lat: 39.9372, lon: -105.5828, timezone: "America/Denver" },
  { name: "Frisco", city: "Frisco", state: "CO", lat: 39.58, lon: -106.1, timezone: "America/Denver" },
  { name: "Granby Ranch", city: "Granby", state: "CO", lat: 40.0414, lon: -105.9156, timezone: "America/Denver" },
  { name: "Hoedown Hill", city: "Colorado Springs", state: "CO", lat: 38.86, lon: -104.88, timezone: "America/Denver" },
  { name: "Howelsen Hill", city: "Steamboat Springs", state: "CO", lat: 40.4847, lon: -106.8375, timezone: "America/Denver" },
  { name: "Kendall Mountain", city: "Silverton", state: "CO", lat: 37.81, lon: -107.66, timezone: "America/Denver" },
  { name: "Keystone", city: "Keystone", state: "CO", lat: 39.6064, lon: -105.9497, timezone: "America/Denver" },
  { name: "Lake City", city: "Lake City", state: "CO", lat: 38.03, lon: -107.32, timezone: "America/Denver" },
  { name: "Lee's", city: "Trinidad", state: "CO", lat: 37.04, lon: -104.72, timezone: "America/Denver" },
  { name: "Loveland Basin", city: "Georgetown", state: "CO", lat: 39.6803, lon: -105.8983, timezone: "America/Denver" },
  { name: "Loveland Valley", city: "Georgetown", state: "CO", lat: 39.6656, lon: -105.8875, timezone: "America/Denver" },
  { name: "Monarch", city: "Monarch", state: "CO", lat: 38.5128, lon: -106.3328, timezone: "America/Denver" },
  { name: "Powderhorn", city: "Mesa", state: "CO", lat: 39.0681, lon: -108.1508, timezone: "America/Denver" },
  { name: "Purgatory", city: "Durango", state: "CO", lat: 37.6303, lon: -107.8142, timezone: "America/Denver" },
  { name: "Silverton", city: "Silverton", state: "CO", lat: 37.8847, lon: -107.6633, timezone: "America/Denver" },
  { name: "Ski Cooper", city: "Leadville", state: "CO", lat: 39.3617, lon: -106.2989, timezone: "America/Denver" },
  { name: "Snowmass", city: "Snowmass Village", state: "CO", lat: 39.2128, lon: -106.9475, timezone: "America/Denver" },
  { name: "Steamboat", city: "Steamboat Springs", state: "CO", lat: 40.4572, lon: -106.8044, timezone: "America/Denver" },
  { name: "Sunlight", city: "Glenwood Springs", state: "CO", lat: 39.3992, lon: -107.3392, timezone: "America/Denver" },
  { name: "Telluride", city: "Telluride", state: "CO", lat: 37.9364, lon: -107.8464, timezone: "America/Denver" },
  { name: "Vail Mountain", city: "Vail", state: "CO", lat: 39.6403, lon: -106.3742, timezone: "America/Denver" },
  { name: "Winter Park", city: "Winter Park", state: "CO", lat: 39.8869, lon: -105.7625, timezone: "America/Denver" },
  { name: "Wolf Creek", city: "Pagosa Springs", state: "CO", lat: 37.4728, lon: -106.7933, timezone: "America/Denver" },
  { name: "Lakeridge", city: "New Milford", state: "CT", lat: 41.42, lon: -73.37, timezone: "America/New_York" },
  { name: "Mohawk Mountain", city: "Cornwall", state: "CT", lat: 41.8392, lon: -73.2964, timezone: "America/New_York" },
  { name: "Mount Southington", city: "Plantsville", state: "CT", lat: 41.6167, lon: -72.8972, timezone: "America/New_York" },
  { name: "Powder Ridge", city: "Middlefield", state: "CT", lat: 41.5175, lon: -72.7036, timezone: "America/New_York" },
  { name: "Ski Sundown", city: "New Hartford", state: "CT", lat: 41.9272, lon: -72.9431, timezone: "America/New_York" },
  { name: "Bald Mountain", city: "Pierce", state: "ID", lat: 42.62, lon: -115.3, timezone: "America/Boise" },
  { name: "Bogus Basin", city: "Boise", state: "ID", lat: 43.7647, lon: -116.1025, timezone: "America/Boise" },
  { name: "Brundage", city: "McCall", state: "ID", lat: 44.9369, lon: -116.1542, timezone: "America/Boise" },
  { name: "Chipmunk Hills", city: "Moscow", state: "ID", lat: 46.44, lon: -116.78, timezone: "America/Boise" },
  { name: "Cottonwood Butte", city: "Cottonwood", state: "ID", lat: 46.02, lon: -116.37, timezone: "America/Boise" },
  { name: "Gateway Parks: Eagle Island", city: "Eagle", state: "ID", lat: 43.66, lon: -116.38, timezone: "America/Boise" },
  { name: "Gateway Parks: Idaho Falls", city: "Idaho Falls", state: "ID", lat: 43.49, lon: -112.03, timezone: "America/Boise" },
  { name: "Kelly Canyon", city: "Ririe", state: "ID", lat: 43.52, lon: -111.57, timezone: "America/Boise" },
  { name: "Little Ski Hill", city: "McCall", state: "ID", lat: 44.1, lon: -116.12, timezone: "America/Boise" },
  { name: "Lookout Pass", city: "Mullan", state: "ID", lat: 47.4544, lon: -115.7036, timezone: "America/Boise" },
  { name: "Magic Mountain", city: "Hansen", state: "ID", lat: 42.21, lon: -114.33, timezone: "America/Boise" },
  { name: "Pebble Creek", city: "Inkom", state: "ID", lat: 42.7625, lon: -112.0936, timezone: "America/Boise" },
  { name: "Pomerelle", city: "Albion", state: "ID", lat: 42.0714, lon: -113.5831, timezone: "America/Boise" },
  { name: "Rotarun", city: "Hailey", state: "ID", lat: 43.48, lon: -114.33, timezone: "America/Boise" },
  { name: "Schweitzer", city: "Sandpoint", state: "ID", lat: 48.3681, lon: -116.6222, timezone: "America/Boise" },
  { name: "Silver Mountain", city: "Kellogg", state: "ID", lat: 47.5386, lon: -116.1278, timezone: "America/Boise" },
  { name: "Snowhaven", city: "Glenns Ferry", state: "ID", lat: 42.39, lon: -115.48, timezone: "America/Boise" },
  { name: "Soldier Mountain", city: "Fairfield", state: "ID", lat: 43.5403, lon: -114.8089, timezone: "America/Boise" },
  { name: "Sun Valley: Bald", city: "Sun Valley", state: "ID", lat: 43.6303, lon: -114.3656, timezone: "America/Boise" },
  { name: "Sun Valley: Dollar", city: "Sun Valley", state: "ID", lat: 43.68, lon: -114.3528, timezone: "America/Boise" },
  { name: "Tamarack", city: "Donnelly", state: "ID", lat: 44.67, lon: -116.11, timezone: "America/Boise" },
  { name: "Alpine Hills Adventure Park", city: "Rockford", state: "IL", lat: 40.94, lon: -90.43, timezone: "America/Chicago" },
  { name: "Chestnut", city: "Galena", state: "IL", lat: 42.47, lon: -89.97, timezone: "America/Chicago" },
  { name: "Fourlakes", city: "Lisle", state: "IL", lat: 42.2, lon: -88.46, timezone: "America/Chicago" },
  { name: "Snowstar", city: "Andalusia", state: "IL", lat: 41.5, lon: -90.53, timezone: "America/Chicago" },
  { name: "Villa Olivia", city: "Bartlett", state: "IL", lat: 41.97, lon: -88.18, timezone: "America/Chicago" },
  { name: "Paoli Peaks", city: "Paoli", state: "IN", lat: 38.5567, lon: -86.4367, timezone: "America/Indiana/Indianapolis" },
  { name: "Perfect North", city: "Lawrenceburg", state: "IN", lat: 39.15, lon: -84.82, timezone: "America/Indiana/Indianapolis" },
  { name: "Crescent Hill at Hitchcock", city: "Crescent", state: "IA", lat: 41.41, lon: -95.83, timezone: "America/Chicago" },
  { name: "Seven Oaks", city: "Boone", state: "IA", lat: 42.1, lon: -94.21, timezone: "America/Chicago" },
  { name: "Sundown", city: "Dubuque", state: "IA", lat: 42.51, lon: -90.98, timezone: "America/Chicago" },
  { name: "Baker", city: "Mapleton", state: "ME", lat: 46.86, lon: -68.17, timezone: "America/New_York" },
  { name: "Big Moose", city: "Greenville", state: "ME", lat: 45.21, lon: -69.4, timezone: "America/New_York" },
  { name: "Bigrock", city: "Mars Hill", state: "ME", lat: 46.67, lon: -68.01, timezone: "America/New_York" },
  { name: "Black Mountain of Maine", city: "Rumford", state: "ME", lat: 44.265, lon: -70.8431, timezone: "America/New_York" },
  { name: "Camden Snow Bowl", city: "Camden", state: "ME", lat: 44.1847, lon: -69.0861, timezone: "America/New_York" },
  { name: "Caribou High School", city: "Caribou", state: "ME", lat: 46.86, lon: -68.01, timezone: "America/New_York" },
  { name: "Hermon Mountain", city: "Hermon", state: "ME", lat: 44.84, lon: -68.89, timezone: "America/New_York" },
  { name: "Lonesome Pine", city: "Fort Kent", state: "ME", lat: 45.01, lon: -69.03, timezone: "America/New_York" },
  { name: "Lost Valley", city: "Auburn", state: "ME", lat: 44.1003, lon: -70.2314, timezone: "America/New_York" },
  { name: "Mount Abram", city: "Greenwood", state: "ME", lat: 44.3694, lon: -70.6797, timezone: "America/New_York" },
  { name: "Mount Jefferson", city: "Lee", state: "ME", lat: 44.56, lon: -70.43, timezone: "America/New_York" },
  { name: "O'Connor (Kent School)", city: "Orono", state: "ME", lat: 44.92, lon: -68.79, timezone: "America/New_York" },
  { name: "Pinnacle", city: "Bangor", state: "ME", lat: 44.92, lon: -68.79, timezone: "America/New_York" },
  { name: "Pleasant Mountain", city: "Bridgton", state: "ME", lat: 44.0269, lon: -70.875, timezone: "America/New_York" },
  { name: "Powderhouse Hill", city: "Bangor", state: "ME", lat: 44.8, lon: -68.76, timezone: "America/New_York" },
  { name: "Quarry Road", city: "Waterville", state: "ME", lat: 44.55, lon: -69.63, timezone: "America/New_York" },
  { name: "Quoggy Joe", city: "Presque Isle", state: "ME", lat: 46.31, lon: -67.87, timezone: "America/New_York" },
  { name: "Saddleback", city: "Rangeley", state: "ME", lat: 44.9342, lon: -70.5036, timezone: "America/New_York" },
  { name: "Spruce Mountain", city: "Jay", state: "ME", lat: 44.65, lon: -70.15, timezone: "America/New_York" },
  { name: "Sugarloaf", city: "Carrabassett Valley", state: "ME", lat: 45.0314, lon: -70.3131, timezone: "America/New_York" },
  { name: "Sunday River", city: "Newry", state: "ME", lat: 44.4728, lon: -70.8567, timezone: "America/New_York" },
  { name: "Titcomb", city: "Farmington", state: "ME", lat: 44.68, lon: -70.12, timezone: "America/New_York" },
  { name: "Wisp", city: "McHenry", state: "MD", lat: 39.5569, lon: -79.3642, timezone: "America/New_York" },
  { name: "Berkshire East", city: "Charlemont", state: "MA", lat: 42.6036, lon: -72.7097, timezone: "America/New_York" },
  { name: "Blue Hills", city: "Canton", state: "MA", lat: 42.2111, lon: -71.1111, timezone: "America/New_York" },
  { name: "Bousquet", city: "Pittsfield", state: "MA", lat: 42.4444, lon: -73.2611, timezone: "America/New_York" },
  { name: "Butternut", city: "Great Barrington", state: "MA", lat: 42.1803, lon: -73.3053, timezone: "America/New_York" },
  { name: "Catamount", city: "South Egremont", state: "MA", lat: 42.1722, lon: -73.4764, timezone: "America/New_York" },
  { name: "Easton (Eaglebrook School)", city: "Deerfield", state: "MA", lat: 42.57, lon: -72.6, timezone: "America/New_York" },
  { name: "Jiminy Peak", city: "Hancock", state: "MA", lat: 42.5508, lon: -73.2669, timezone: "America/New_York" },
  { name: "Mt. Greylock Ski Club", city: "Williamstown", state: "MA", lat: 42.62, lon: -73.17, timezone: "America/New_York" },
  { name: "Nashoba Valley", city: "Westford", state: "MA", lat: 42.5339, lon: -71.4461, timezone: "America/New_York" },
  { name: "Otis Ridge", city: "Otis", state: "MA", lat: 42.18, lon: -73.08, timezone: "America/New_York" },
  { name: "Ski Bradford", city: "Haverhill", state: "MA", lat: 42.7506, lon: -71.0817, timezone: "America/New_York" },
  { name: "Ski Ward", city: "Shrewsbury", state: "MA", lat: 42.53, lon: -71.69, timezone: "America/New_York" },
  { name: "Wachusett", city: "Princeton", state: "MA", lat: 42.5039, lon: -71.8847, timezone: "America/New_York" },
  { name: "Adventure Mountain (UP)", city: "Greenwood", state: "MI", lat: 46.5236, lon: -87.4258, timezone: "America/Detroit" },
  { name: "Alpine Valley MI", city: "White Lake", state: "MI", lat: 42.7653, lon: -83.5475, timezone: "America/Detroit" },
  { name: "Big Powderhorn (UP)", city: "Bessemer", state: "MI", lat: 46.5028, lon: -90.0608, timezone: "America/Detroit" },
  { name: "Big Valley (UP)", city: "Rapid River", state: "MI", lat: 45.93, lon: -87.24, timezone: "America/Detroit" },
  { name: "Bittersweet", city: "Otsego", state: "MI", lat: 42.1439, lon: -85.7694, timezone: "America/Detroit" },
  { name: "Boyne Mountain", city: "Boyne Falls", state: "MI", lat: 45.1628, lon: -84.9372, timezone: "America/Detroit" },
  { name: "Caberfae Peaks", city: "Cadillac", state: "MI", lat: 44.2414, lon: -85.7592, timezone: "America/Detroit" },
  { name: "Cannonsburg", city: "Cannonsburg", state: "MI", lat: 43.05, lon: -85.51, timezone: "America/Detroit" },
  { name: "Challenge Mountain", city: "Walloon Lake", state: "MI", lat: 45.32, lon: -84.96, timezone: "America/Detroit" },
  { name: "Covington (UP)", city: "Covington", state: "MI", lat: 46.64, lon: -88.59, timezone: "America/Detroit" },
  { name: "Crystal Mountain MI", city: "Thompsonville", state: "MI", lat: 44.5236, lon: -86.0022, timezone: "America/Detroit" },
  { name: "Crystella (UP)", city: "Ishpeming", state: "MI", lat: 46.24, lon: -87.07, timezone: "America/Detroit" },
  { name: "Gladstone (UP)", city: "Gladstone", state: "MI", lat: 45.85, lon: -87.02, timezone: "America/Detroit" },
  { name: "Hanson Hills", city: "Grayling", state: "MI", lat: 44.69, lon: -84.61, timezone: "America/Detroit" },
  { name: "Hiawatha (UP)", city: "Gaastra", state: "MI", lat: 46.35, lon: -86.93, timezone: "America/Detroit" },
  { name: "Hickory Hills", city: "Traverse City", state: "MI", lat: 44.77, lon: -85.62, timezone: "America/Detroit" },
  { name: "Homestead", city: "Glen Arbor", state: "MI", lat: 44.8592, lon: -85.9267, timezone: "America/Detroit" },
  { name: "Marquette Mountain (UP)", city: "Marquette", state: "MI", lat: 46.4956, lon: -87.4258, timezone: "America/Detroit" },
  { name: "Missaukee Mountain", city: "Lake City", state: "MI", lat: 44.31, lon: -85.14, timezone: "America/Detroit" },
  { name: "Mont Ripley (UP)", city: "Hancock", state: "MI", lat: 47.1208, lon: -88.5453, timezone: "America/Detroit" },
  { name: "Mount Bohemia (UP)", city: "Lac La Belle", state: "MI", lat: 47.3942, lon: -88.0117, timezone: "America/Detroit" },
  { name: "Mount Brighton", city: "Brighton", state: "MI", lat: 42.5317, lon: -83.8203, timezone: "America/Detroit" },
  { name: "Mount Holiday", city: "Traverse City", state: "MI", lat: 44.85, lon: -85.46, timezone: "America/Detroit" },
  { name: "Mount Holly", city: "Holly", state: "MI", lat: 42.8025, lon: -83.5342, timezone: "America/Detroit" },
  { name: "Mount McSauba", city: "Charlevoix", state: "MI", lat: 45.31, lon: -85.28, timezone: "America/Detroit" },
  { name: "Mount Zion (UP)", city: "Ironwood", state: "MI", lat: 46.21, lon: -86.28, timezone: "America/Detroit" },
  { name: "Mulligan's Hollow", city: "Grand Haven", state: "MI", lat: 42.87, lon: -86.1, timezone: "America/Detroit" },
  { name: "Norway Mountain", city: "Norway", state: "MI", lat: 45.8161, lon: -87.8708, timezone: "America/Detroit" },
  { name: "Nub's Nob", city: "Harbor Springs", state: "MI", lat: 45.4681, lon: -84.9147, timezone: "America/Detroit" },
  { name: "Otsego", city: "Gaylord", state: "MI", lat: 44.97, lon: -84.66, timezone: "America/Detroit" },
  { name: "Pine Knob", city: "Clarkston", state: "MI", lat: 42.755, lon: -83.3933, timezone: "America/Detroit" },
  { name: "Pine Mountain (UP)", city: "Iron Mountain", state: "MI", lat: 45.8231, lon: -88.0764, timezone: "America/Detroit" },
  { name: "Porcupine Mountains (UP)", city: "Ontonagon", state: "MI", lat: 46.8008, lon: -89.7567, timezone: "America/Detroit" },
  { name: "Sault Seal (UP)", city: "Sault Ste. Marie", state: "MI", lat: 46.52, lon: -84.39, timezone: "America/Detroit" },
  { name: "Shanty Creek - Schuss", city: "Bellaire", state: "MI", lat: 44.9292, lon: -85.1753, timezone: "America/Detroit" },
  { name: "Ski Brule (UP)", city: "Iron River", state: "MI", lat: 46.0817, lon: -88.3958, timezone: "America/Detroit" },
  { name: "Snow Snake", city: "Harrison", state: "MI", lat: 43.35, lon: -84.72, timezone: "America/Detroit" },
  { name: "Snowriver: Black River (UP)", city: "Wakefield", state: "MI", lat: 46.71, lon: -88.92, timezone: "America/Detroit" },
  { name: "Snowriver: Jackson Creek (UP)", city: "Greenland", state: "MI", lat: 46.43, lon: -88.04, timezone: "America/Detroit" },
  { name: "Swiss Valley", city: "Jones", state: "MI", lat: 41.8656, lon: -86.1472, timezone: "America/Detroit" },
  { name: "The Highlands", city: "Harbor Springs", state: "MI", lat: 45.03, lon: -84.61, timezone: "America/Detroit" },
  { name: "Timber Ridge", city: "Gobles", state: "MI", lat: 42.3422, lon: -85.2592, timezone: "America/Detroit" },
  { name: "Tower Mountain", city: "Ishpeming", state: "MI", lat: 46.46, lon: -87.0, timezone: "America/Detroit" },
  { name: "Treetops", city: "Gaylord", state: "MI", lat: 45.0478, lon: -84.6664, timezone: "America/Detroit" },
  { name: "Afton Alps", city: "Hastings", state: "MN", lat: 44.8553, lon: -92.7856, timezone: "America/Chicago" },
  { name: "Andes Tower Hills", city: "Kensington", state: "MN", lat: 45.85, lon: -95.67, timezone: "America/Chicago" },
  { name: "Buck Hill", city: "Burnsville", state: "MN", lat: 44.7208, lon: -93.2878, timezone: "America/Chicago" },
  { name: "Buena Vista", city: "Bemidji", state: "MN", lat: 46.04, lon: -93.73, timezone: "America/Chicago" },
  { name: "Chester Bowl", city: "Duluth", state: "MN", lat: 46.8, lon: -92.08, timezone: "America/Chicago" },
  { name: "Cloquet Nordic Ski Club", city: "Cloquet", state: "MN", lat: 46.72, lon: -92.46, timezone: "America/Chicago" },
  { name: "Coffee Mill", city: "Wabasha", state: "MN", lat: 44.41, lon: -91.9, timezone: "America/Chicago" },
  { name: "Como Park Ski Center", city: "St. Paul", state: "MN", lat: 44.98, lon: -93.14, timezone: "America/Chicago" },
  { name: "Detroit Mountain", city: "Detroit Lakes", state: "MN", lat: 46.83, lon: -95.77, timezone: "America/Chicago" },
  { name: "Elm Creek", city: "Maple Grove", state: "MN", lat: 45.15, lon: -93.44, timezone: "America/Chicago" },
  { name: "Giants Ridge", city: "Biwabik", state: "MN", lat: 47.5592, lon: -92.4722, timezone: "America/Chicago" },
  { name: "Hyland Hills", city: "Bloomington", state: "MN", lat: 44.84, lon: -93.37, timezone: "America/Chicago" },
  { name: "Lutsen Mountains", city: "Lutsen", state: "MN", lat: 47.6572, lon: -90.7125, timezone: "America/Chicago" },
  { name: "Mount Itasca", city: "Coleraine", state: "MN", lat: 47.21, lon: -93.6, timezone: "America/Chicago" },
  { name: "Mount Kato", city: "Mankato", state: "MN", lat: 44.1253, lon: -94.0192, timezone: "America/Chicago" },
  { name: "Mount Ski Gull", city: "Nisswa", state: "MN", lat: 46.43, lon: -94.43, timezone: "America/Chicago" },
  { name: "Powder Ridge MN", city: "Kimball", state: "MN", lat: 45.4847, lon: -94.4089, timezone: "America/Chicago" },
  { name: "Spirit Mountain", city: "Duluth", state: "MN", lat: 46.7194, lon: -92.2186, timezone: "America/Chicago" },
  { name: "Steeplechase", city: "St. Michael", state: "MN", lat: 45.27, lon: -93.78, timezone: "America/Chicago" },
  { name: "Welch Village", city: "Welch", state: "MN", lat: 44.5647, lon: -92.7206, timezone: "America/Chicago" },
  { name: "Wild Mountain", city: "Taylors Falls", state: "MN", lat: 45.4597, lon: -92.7397, timezone: "America/Chicago" },
  { name: "Hidden Valley", city: "Wildwood", state: "MO", lat: 38.5158, lon: -90.71, timezone: "America/Chicago" },
  { name: "Snow Creek", city: "Weston", state: "MO", lat: 39.5428, lon: -94.8436, timezone: "America/Chicago" },
  { name: "Bear Canyon", city: "Bozeman", state: "MT", lat: 45.69, lon: -110.91, timezone: "America/Denver" },
  { name: "Bear Paw", city: "Havre", state: "MT", lat: 48.08, lon: -109.93, timezone: "America/Denver" },
  { name: "Big Sky", city: "Big Sky", state: "MT", lat: 45.2856, lon: -111.4019, timezone: "America/Denver" },
  { name: "Blacktail", city: "Lakeside", state: "MT", lat: 45.5, lon: -112.69, timezone: "America/Denver" },
  { name: "Bridger Bowl", city: "Bozeman", state: "MT", lat: 45.8175, lon: -110.8967, timezone: "America/Denver" },
  { name: "Discovery", city: "Anaconda", state: "MT", lat: 46.2489, lon: -113.2367, timezone: "America/Denver" },
  { name: "Great Divide", city: "Marysville", state: "MT", lat: 46.7531, lon: -112.3333, timezone: "America/Denver" },
  { name: "Lost Trail", city: "Sula", state: "MT", lat: 45.6936, lon: -113.9494, timezone: "America/Denver" },
  { name: "Maverick Mountain", city: "Polaris", state: "MT", lat: 45.4975, lon: -113.1469, timezone: "America/Denver" },
  { name: "Montana Snowbowl", city: "Missoula", state: "MT", lat: 47.0169, lon: -113.9944, timezone: "America/Denver" },
  { name: "Red Lodge", city: "Red Lodge", state: "MT", lat: 45.1875, lon: -109.3403, timezone: "America/Denver" },
  { name: "Showdown", city: "Neihart", state: "MT", lat: 46.8508, lon: -110.7133, timezone: "America/Denver" },
  { name: "Teton Pass", city: "Choteau", state: "MT", lat: 47.9333, lon: -112.1167, timezone: "America/Denver" },
  { name: "Turner", city: "Turner", state: "MT", lat: 48.86, lon: -108.41, timezone: "America/Denver" },
  { name: "Whitefish", city: "Whitefish", state: "MT", lat: 48.4839, lon: -114.3575, timezone: "America/Denver" },
  { name: "Yellowstone Club", city: "Big Sky", state: "MT", lat: 45.2342, lon: -111.4511, timezone: "America/Denver" },
  { name: "Diamond Peak", city: "Incline Village", state: "NV", lat: 39.2536, lon: -119.9217, timezone: "America/Los_Angeles" },
  { name: "Elko Snobowl", city: "Elko", state: "NV", lat: 40.78, lon: -115.7, timezone: "America/Los_Angeles" },
  { name: "Lee Canyon", city: "Las Vegas", state: "NV", lat: 36.2983, lon: -115.6783, timezone: "America/Los_Angeles" },
  { name: "Mt. Rose", city: "Reno", state: "NV", lat: 39.3147, lon: -119.8856, timezone: "America/Los_Angeles" },
  { name: "Sky Tavern", city: "Reno", state: "NV", lat: 39.31, lon: -119.87, timezone: "America/Los_Angeles" },
  { name: "Abenaki", city: "Wolfeboro", state: "NH", lat: 43.61, lon: -71.22, timezone: "America/New_York" },
  { name: "Arrowhead", city: "Claremont", state: "NH", lat: 43.17, lon: -72.24, timezone: "America/New_York" },
  { name: "Attitash", city: "Bartlett", state: "NH", lat: 44.0822, lon: -71.2297, timezone: "America/New_York" },
  { name: "Black Mountain NH", city: "Jackson", state: "NH", lat: 44.1317, lon: -71.1783, timezone: "America/New_York" },
  { name: "Bretton Woods", city: "Bretton Woods", state: "NH", lat: 44.2644, lon: -71.4642, timezone: "America/New_York" },
  { name: "Campton", city: "Campton", state: "NH", lat: 43.86, lon: -71.64, timezone: "America/New_York" },
  { name: "Cannon", city: "Franconia", state: "NH", lat: 44.1567, lon: -71.6975, timezone: "America/New_York" },
  { name: "Clancy (Cardigan Mtn School)", city: "Canaan", state: "NH", lat: 43.61, lon: -71.91, timezone: "America/New_York" },
  { name: "Cranmore", city: "North Conway", state: "NH", lat: 44.0533, lon: -71.1061, timezone: "America/New_York" },
  { name: "Crotched", city: "Bennington", state: "NH", lat: 42.9939, lon: -71.8717, timezone: "America/New_York" },
  { name: "Dartmouth Skiway", city: "Lyme", state: "NH", lat: 43.7753, lon: -72.0803, timezone: "America/New_York" },
  { name: "Granite Gorge", city: "Keene", state: "NH", lat: 42.9072, lon: -72.2106, timezone: "America/New_York" },
  { name: "Gunstock", city: "Gilford", state: "NH", lat: 43.5389, lon: -71.3656, timezone: "America/New_York" },
  { name: "Kanc Recreation Area", city: "Lincoln", state: "NH", lat: 44.0206, lon: -71.7225, timezone: "America/New_York" },
  { name: "King Pine", city: "East Madison", state: "NH", lat: 43.8578, lon: -71.0781, timezone: "America/New_York" },
  { name: "Loon", city: "Lincoln", state: "NH", lat: 44.0364, lon: -71.6214, timezone: "America/New_York" },
  { name: "McIntyre", city: "Manchester", state: "NH", lat: 43.01, lon: -71.43, timezone: "America/New_York" },
  { name: "Mount Eustis", city: "Littleton", state: "NH", lat: 44.51, lon: -71.57, timezone: "America/New_York" },
  { name: "Mount Sunapee", city: "Newbury", state: "NH", lat: 43.3267, lon: -72.0786, timezone: "America/New_York" },
  { name: "Norm Wright (Dublin School)", city: "Dublin", state: "NH", lat: 42.91, lon: -72.06, timezone: "America/New_York" },
  { name: "Pats Peak", city: "Henniker", state: "NH", lat: 43.1717, lon: -71.7917, timezone: "America/New_York" },
  { name: "Proctor", city: "Andover", state: "NH", lat: 43.43, lon: -72.08, timezone: "America/New_York" },
  { name: "Ragged", city: "Danbury", state: "NH", lat: 43.4706, lon: -71.8375, timezone: "America/New_York" },
  { name: "Red Hill", city: "Moultonborough", state: "NH", lat: 43.88, lon: -71.66, timezone: "America/New_York" },
  { name: "Storrs Hill", city: "Lebanon", state: "NH", lat: 43.64, lon: -72.25, timezone: "America/New_York" },
  { name: "Tenney", city: "Plymouth", state: "NH", lat: 43.71, lon: -71.34, timezone: "America/New_York" },
  { name: "Veterans Memorial", city: "Franklin", state: "NH", lat: 43.08, lon: -71.53, timezone: "America/New_York" },
  { name: "Waterville Valley", city: "Waterville Valley", state: "NH", lat: 43.9503, lon: -71.5283, timezone: "America/New_York" },
  { name: "Whaleback Mountain", city: "Enfield", state: "NH", lat: 43.5331, lon: -72.1386, timezone: "America/New_York" },
  { name: "Wildcat", city: "Gorham", state: "NH", lat: 44.2636, lon: -71.2394, timezone: "America/New_York" },
  { name: "Big Snow American Dream", city: "East Rutherford", state: "NJ", lat: 40.8144, lon: -74.0736, timezone: "America/New_York" },
  { name: "Campgaw", city: "Mahwah", state: "NJ", lat: 41.0633, lon: -74.1781, timezone: "America/New_York" },
  { name: "Mountain Creek", city: "Vernon", state: "NJ", lat: 41.1778, lon: -74.5019, timezone: "America/New_York" },
  { name: "National Winter Activity Center", city: "Vernon", state: "NJ", lat: 40.92, lon: -74.52, timezone: "America/New_York" },
  { name: "Angel Fire Resort", city: "Angel Fire", state: "NM", lat: 36.3925, lon: -105.2878, timezone: "America/Denver" },
  { name: "Cloudcroft", city: "Cloudcroft", state: "NM", lat: 32.955, lon: -105.74, timezone: "America/Denver" },
  { name: "Pajarito", city: "Los Alamos", state: "NM", lat: 35.8947, lon: -106.3939, timezone: "America/Denver" },
  { name: "Red River", city: "Red River", state: "NM", lat: 36.6675, lon: -105.3792, timezone: "America/Denver" },
  { name: "Sandia Peak", city: "Albuquerque", state: "NM", lat: 35.2106, lon: -106.4192, timezone: "America/Denver" },
  { name: "Sipapu", city: "Vadito", state: "NM", lat: 36.0933, lon: -105.5153, timezone: "America/Denver" },
  { name: "Ski Apache", city: "Ruidoso", state: "NM", lat: 33.4036, lon: -105.7875, timezone: "America/Denver" },
  { name: "Ski Santa Fe", city: "Santa Fe", state: "NM", lat: 35.7956, lon: -105.8025, timezone: "America/Denver" },
  { name: "Taos Ski Valley", city: "Taos Ski Valley", state: "NM", lat: 36.5967, lon: -105.4547, timezone: "America/Denver" },
  { name: "Beartown", city: "Richmondville", state: "NY", lat: 42.76, lon: -74.62, timezone: "America/New_York" },
  { name: "Belleayre", city: "Highmount", state: "NY", lat: 42.1356, lon: -74.5081, timezone: "America/New_York" },
  { name: "Brantling", city: "Sodus", state: "NY", lat: 43.13, lon: -77.42, timezone: "America/New_York" },
  { name: "Bristol", city: "Canandaigua", state: "NY", lat: 42.7569, lon: -77.4139, timezone: "America/New_York" },
  { name: "Buffalo Ski Center", city: "Buffalo", state: "NY", lat: 42.94, lon: -78.75, timezone: "America/New_York" },
  { name: "Camillus", city: "Camillus", state: "NY", lat: 43.04, lon: -76.31, timezone: "America/New_York" },
  { name: "Cazenovia Ski Club", city: "Cazenovia", state: "NY", lat: 42.93, lon: -75.85, timezone: "America/New_York" },
  { name: "Chestnut Ridge", city: "Orchard Park", state: "NY", lat: 42.67, lon: -78.8, timezone: "America/New_York" },
  { name: "Double H Ranch", city: "Lake Luzerne", state: "NY", lat: 43.71, lon: -73.97, timezone: "America/New_York" },
  { name: "Dry Hill", city: "Watertown", state: "NY", lat: 43.71, lon: -75.48, timezone: "America/New_York" },
  { name: "Dynamite Hill", city: "Chestertown", state: "NY", lat: 43.41, lon: -73.77, timezone: "America/New_York" },
  { name: "Emery County Park", city: "Owego", state: "NY", lat: 42.05, lon: -76.82, timezone: "America/New_York" },
  { name: "Gore", city: "North Creek", state: "NY", lat: 43.6728, lon: -74.0028, timezone: "America/New_York" },
  { name: "Greek Peak", city: "Cortland", state: "NY", lat: 42.5097, lon: -76.1453, timezone: "America/New_York" },
  { name: "Holiday Mountain NY", city: "Monticello", state: "NY", lat: 41.6167, lon: -74.6944, timezone: "America/New_York" },
  { name: "Holiday Valley", city: "Ellicottville", state: "NY", lat: 42.2675, lon: -78.6742, timezone: "America/New_York" },
  { name: "Holimont", city: "Ellicottville", state: "NY", lat: 42.2642, lon: -78.6794, timezone: "America/New_York" },
  { name: "Hunt Hollow", city: "Naples", state: "NY", lat: 42.54, lon: -77.59, timezone: "America/New_York" },
  { name: "Hunter", city: "Hunter", state: "NY", lat: 42.2, lon: -74.2219, timezone: "America/New_York" },
  { name: "Kissing Bridge", city: "Glenwood", state: "NY", lat: 42.6058, lon: -78.7103, timezone: "America/New_York" },
  { name: "Labrador", city: "Truxton", state: "NY", lat: 42.4756, lon: -76.0764, timezone: "America/New_York" },
  { name: "Maple Ski Ridge", city: "Schenectady", state: "NY", lat: 42.84, lon: -73.94, timezone: "America/New_York" },
  { name: "McCauley", city: "Old Forge", state: "NY", lat: 43.7331, lon: -74.9669, timezone: "America/New_York" },
  { name: "Mount Peter", city: "Warwick", state: "NY", lat: 41.2317, lon: -74.3097, timezone: "America/New_York" },
  { name: "Mount Pisgah", city: "Saranac Lake", state: "NY", lat: 43.82, lon: -74.91, timezone: "America/New_York" },
  { name: "Newcomb", city: "Newcomb", state: "NY", lat: 43.97, lon: -74.15, timezone: "America/New_York" },
  { name: "Northampton", city: "Northville", state: "NY", lat: 43.13, lon: -74.2, timezone: "America/New_York" },
  { name: "Oak Mountain", city: "Speculator", state: "NY", lat: 43.2978, lon: -74.4481, timezone: "America/New_York" },
  { name: "Peek'n Peak", city: "Clymer", state: "NY", lat: 42.0575, lon: -79.7339, timezone: "America/New_York" },
  { name: "Plattekill", city: "Roxbury", state: "NY", lat: 42.2667, lon: -74.6525, timezone: "America/New_York" },
  { name: "Powder Mills", city: "Pittsford", state: "NY", lat: 43.1, lon: -77.47, timezone: "America/New_York" },
  { name: "Ridin' Hy Ranch", city: "Warrensburg", state: "NY", lat: 43.64, lon: -73.74, timezone: "America/New_York" },
  { name: "Rocking Horse Ranch", city: "Highland", state: "NY", lat: 41.77, lon: -74.19, timezone: "America/New_York" },
  { name: "Royal Mountain", city: "Caroga Lake", state: "NY", lat: 43.0597, lon: -74.5589, timezone: "America/New_York" },
  { name: "Skaneateles", city: "Skaneateles", state: "NY", lat: 42.92, lon: -76.4, timezone: "America/New_York" },
  { name: "Ski Venture", city: "Durham", state: "NY", lat: 42.42, lon: -74.23, timezone: "America/New_York" },
  { name: "Snow Ridge", city: "Turin", state: "NY", lat: 43.6636, lon: -75.4156, timezone: "America/New_York" },
  { name: "Song Mountain", city: "Tully", state: "NY", lat: 42.85, lon: -76.0839, timezone: "America/New_York" },
  { name: "Swain", city: "Swain", state: "NY", lat: 42.4833, lon: -77.8583, timezone: "America/New_York" },
  { name: "Thunder Ridge", city: "Patterson", state: "NY", lat: 41.5006, lon: -73.5108, timezone: "America/New_York" },
  { name: "Titus", city: "Titusville", state: "NY", lat: 42.4772, lon: -77.0647, timezone: "America/New_York" },
  { name: "Val Bialis", city: "Phoenicia", state: "NY", lat: 42.18, lon: -74.45, timezone: "America/New_York" },
  { name: "Victor Constant", city: "West Point", state: "NY", lat: 41.39, lon: -73.96, timezone: "America/New_York" },
  { name: "Villa Roma", city: "Callicoon", state: "NY", lat: 41.68, lon: -74.83, timezone: "America/New_York" },
  { name: "West Mountain", city: "Queensbury", state: "NY", lat: 43.2881, lon: -73.7836, timezone: "America/New_York" },
  { name: "Whiteface", city: "Wilmington", state: "NY", lat: 44.3658, lon: -73.9033, timezone: "America/New_York" },
  { name: "Willard", city: "Willard", state: "NY", lat: 42.34, lon: -77.38, timezone: "America/New_York" },
  { name: "Windham", city: "Windham", state: "NY", lat: 42.2969, lon: -74.2558, timezone: "America/New_York" },
  { name: "Woods Valley", city: "Westernville", state: "NY", lat: 43.3536, lon: -75.0575, timezone: "America/New_York" },
  { name: "Appalachian Ski Mountain", city: "Blowing Rock", state: "NC", lat: 36.0931, lon: -81.6778, timezone: "America/New_York" },
  { name: "Beech Mountain", city: "Beech Mountain", state: "NC", lat: 36.1808, lon: -81.8883, timezone: "America/New_York" },
  { name: "Cataloochee", city: "Maggie Valley", state: "NC", lat: 35.5678, lon: -83.0958, timezone: "America/New_York" },
  { name: "Hatley Pointe", city: "Conover", state: "NC", lat: 35.76, lon: -81.32, timezone: "America/New_York" },
  { name: "Sapphire Valley", city: "Sapphire", state: "NC", lat: 35.1164, lon: -82.9833, timezone: "America/New_York" },
  { name: "Sugar Mountain", city: "Banner Elk", state: "NC", lat: 36.1175, lon: -81.8669, timezone: "America/New_York" },
  { name: "Bottineau Winter Park", city: "Bottineau", state: "ND", lat: 48.9206, lon: -100.3867, timezone: "America/Chicago" },
  { name: "Frost Fire", city: "Walhalla", state: "ND", lat: 48.98, lon: -100.98, timezone: "America/Chicago" },
  { name: "Huff Hills", city: "Mandan", state: "ND", lat: 46.66, lon: -100.58, timezone: "America/Chicago" },
  { name: "Thrill Hills", city: "Fargo", state: "ND", lat: 46.88, lon: -97.02, timezone: "America/Chicago" },
  { name: "Alpine Valley OH", city: "Chesterland", state: "OH", lat: 41.62, lon: -81.0483, timezone: "America/New_York" },
  { name: "Big Creek Ski Area", city: "Cleveland", state: "OH", lat: 41.46, lon: -81.47, timezone: "America/New_York" },
  { name: "Boston Mills", city: "Peninsula", state: "OH", lat: 41.2625, lon: -81.5531, timezone: "America/New_York" },
  { name: "Brandywine", city: "Sagamore Hills", state: "OH", lat: 41.2736, lon: -81.5264, timezone: "America/New_York" },
  { name: "Mad River", city: "Zanesfield", state: "OH", lat: 40.2928, lon: -83.7611, timezone: "America/New_York" },
  { name: "Snow Trails", city: "Mansfield", state: "OH", lat: 40.6619, lon: -82.5392, timezone: "America/New_York" },
  { name: "Anthony Lakes", city: "North Powder", state: "OR", lat: 44.9594, lon: -118.2306, timezone: "America/Los_Angeles" },
  { name: "Cooper Spur", city: "Mount Hood", state: "OR", lat: 45.4169, lon: -121.6028, timezone: "America/Los_Angeles" },
  { name: "Ferguson Ridge", city: "Joseph", state: "OR", lat: 45.31, lon: -117.13, timezone: "America/Los_Angeles" },
  { name: "Hoodoo", city: "Sisters", state: "OR", lat: 44.4086, lon: -121.8722, timezone: "America/Los_Angeles" },
  { name: "Mount Ashland", city: "Ashland", state: "OR", lat: 42.0828, lon: -122.7231, timezone: "America/Los_Angeles" },
  { name: "Mount Bachelor", city: "Bend", state: "OR", lat: 43.9792, lon: -121.6889, timezone: "America/Los_Angeles" },
  { name: "Mount Hood Meadows", city: "Mount Hood", state: "OR", lat: 45.3353, lon: -121.665, timezone: "America/Los_Angeles" },
  { name: "Mount Hood Skibowl", city: "Government Camp", state: "OR", lat: 45.3019, lon: -121.7711, timezone: "America/Los_Angeles" },
  { name: "Timberline Lodge", city: "Government Camp", state: "OR", lat: 45.3311, lon: -121.7111, timezone: "America/Los_Angeles" },
  { name: "Warner Canyon", city: "Lakeview", state: "OR", lat: 42.21, lon: -120.36, timezone: "America/Los_Angeles" },
  { name: "Willamette Pass", city: "Crescent", state: "OR", lat: 43.5989, lon: -122.0403, timezone: "America/Los_Angeles" },
  { name: "Bear Creek", city: "Macungie", state: "PA", lat: 41.04, lon: -75.62, timezone: "America/New_York" },
  { name: "Big Boulder", city: "Lake Harmony", state: "PA", lat: 41.1072, lon: -75.5736, timezone: "America/New_York" },
  { name: "Blue Knob", city: "Claysburg", state: "PA", lat: 40.2875, lon: -78.5656, timezone: "America/New_York" },
  { name: "Blue Mountain PA", city: "Palmerton", state: "PA", lat: 40.8247, lon: -76.0267, timezone: "America/New_York" },
  { name: "Boyce Park", city: "Plum", state: "PA", lat: 40.44, lon: -79.8, timezone: "America/New_York" },
  { name: "Camelback", city: "Tannersville", state: "PA", lat: 41.0478, lon: -75.3572, timezone: "America/New_York" },
  { name: "Eagle Rock", city: "Hazleton", state: "PA", lat: 40.96, lon: -75.9, timezone: "America/New_York" },
  { name: "Elk Mountain", city: "Union Dale", state: "PA", lat: 41.6489, lon: -75.5842, timezone: "America/New_York" },
  { name: "Hidden Valley PA", city: "Hidden Valley", state: "PA", lat: 40.0522, lon: -79.2536, timezone: "America/New_York" },
  { name: "Jack Frost", city: "Blakeslee", state: "PA", lat: 41.11, lon: -75.5386, timezone: "America/New_York" },
  { name: "Laurel", city: "Jennerstown", state: "PA", lat: 40.04, lon: -79.21, timezone: "America/New_York" },
  { name: "Liberty", city: "Fairfield", state: "PA", lat: 39.7656, lon: -77.3742, timezone: "America/New_York" },
  { name: "Locust Lake Village", city: "Barnesville", state: "PA", lat: 40.84, lon: -76.22, timezone: "America/New_York" },
  { name: "Montage", city: "Scranton", state: "PA", lat: 41.3706, lon: -75.6261, timezone: "America/New_York" },
  { name: "Mount Pleasant", city: "Pottstown", state: "PA", lat: 40.23, lon: -75.39, timezone: "America/New_York" },
  { name: "Roundtop", city: "Lewisberry", state: "PA", lat: 40.105, lon: -76.9303, timezone: "America/New_York" },
  { name: "Saw Creek", city: "Bushkill", state: "PA", lat: 41.08, lon: -75.18, timezone: "America/New_York" },
  { name: "Seven Springs", city: "Champion", state: "PA", lat: 40.0233, lon: -79.2975, timezone: "America/New_York" },
  { name: "Shawnee Mountain", city: "Shawnee on Delaware", state: "PA", lat: 41.005, lon: -75.0603, timezone: "America/New_York" },
  { name: "Ski Big Bear", city: "Lackawaxen", state: "PA", lat: 41.16, lon: -75.14, timezone: "America/New_York" },
  { name: "Ski Sawmill", city: "Morris", state: "PA", lat: 41.65, lon: -77.24, timezone: "America/New_York" },
  { name: "Spring Mountain", city: "Spring Mount", state: "PA", lat: 40.275, lon: -75.4539, timezone: "America/New_York" },
  { name: "The Hideout", city: "Lake Ariel", state: "PA", lat: 41.44, lon: -75.32, timezone: "America/New_York" },
  { name: "The Peak at Nemacolin", city: "Farmington", state: "PA", lat: 39.84, lon: -79.61, timezone: "America/New_York" },
  { name: "Tussey", city: "Boalsburg", state: "PA", lat: 40.7608, lon: -77.8217, timezone: "America/New_York" },
  { name: "Whitetail", city: "Mercersburg", state: "PA", lat: 39.7422, lon: -77.9306, timezone: "America/New_York" },
  { name: "Yawgoo", city: "Exeter", state: "RI", lat: 41.5233, lon: -71.6119, timezone: "America/New_York" },
  { name: "Deer Mountain", city: "Lead", state: "SD", lat: 44.3433, lon: -103.82, timezone: "America/Chicago" },
  { name: "Great Bear", city: "Sioux Falls", state: "SD", lat: 43.8339, lon: -96.7592, timezone: "America/Chicago" },
  { name: "Terry Peak", city: "Lead", state: "SD", lat: 44.3678, lon: -103.8439, timezone: "America/Chicago" },
  { name: "Ober Mountain", city: "Gatlinburg", state: "TN", lat: 35.7353, lon: -83.5361, timezone: "America/New_York" },
  { name: "Alta", city: "Alta", state: "UT", lat: 40.5883, lon: -111.6386, timezone: "America/Denver" },
  { name: "Beaver Mountain", city: "Garden City", state: "UT", lat: 41.9683, lon: -111.5439, timezone: "America/Denver" },
  { name: "Brian Head", city: "Brian Head", state: "UT", lat: 37.7025, lon: -112.8489, timezone: "America/Denver" },
  { name: "Brighton", city: "Brighton", state: "UT", lat: 40.598, lon: -111.5833, timezone: "America/Denver" },
  { name: "Buckskin", city: "Huntsville", state: "UT", lat: 41.91, lon: -111.7, timezone: "America/Denver" },
  { name: "Cherry Peak", city: "Richmond", state: "UT", lat: 41.9286, lon: -111.7558, timezone: "America/Denver" },
  { name: "Deer Valley", city: "Park City", state: "UT", lat: 40.6375, lon: -111.4783, timezone: "America/Denver" },
  { name: "Eagle Point", city: "Beaver", state: "UT", lat: 38.3203, lon: -112.3831, timezone: "America/Denver" },
  { name: "Gateway Parks Salt Lake", city: "Salt Lake City", state: "UT", lat: 40.76, lon: -111.89, timezone: "America/Denver" },
  { name: "Gateway Spanish Forks", city: "Spanish Fork", state: "UT", lat: 40.11, lon: -111.64, timezone: "America/Denver" },
  { name: "Nordic Valley", city: "Eden", state: "UT", lat: 41.31, lon: -111.8647, timezone: "America/Denver" },
  { name: "Park City", city: "Park City", state: "UT", lat: 40.6514, lon: -111.508, timezone: "America/Denver" },
  { name: "Powder Mountain", city: "Eden", state: "UT", lat: 41.3797, lon: -111.7794, timezone: "America/Denver" },
  { name: "Snowbasin", city: "Huntsville", state: "UT", lat: 41.2169, lon: -111.8569, timezone: "America/Denver" },
  { name: "Snowbird", city: "Snowbird", state: "UT", lat: 40.583, lon: -111.6508, timezone: "America/Denver" },
  { name: "Snowland", city: "West Jordan", state: "UT", lat: 40.54, lon: -111.98, timezone: "America/Denver" },
  { name: "Solitude", city: "Solitude", state: "UT", lat: 40.6197, lon: -111.5917, timezone: "America/Denver" },
  { name: "Sundance", city: "Sundance", state: "UT", lat: 40.3931, lon: -111.5872, timezone: "America/Denver" },
  { name: "Utah Olympic Park", city: "Park City", state: "UT", lat: 40.7139, lon: -111.5542, timezone: "America/Denver" },
  { name: "Wasatch Peaks Ranch", city: "Huntsville", state: "UT", lat: 41.32, lon: -111.49, timezone: "America/Denver" },
  { name: "Woodward Park City", city: "Park City", state: "UT", lat: 40.7311, lon: -111.5269, timezone: "America/Denver" },
  { name: "77 Winter Sports Park", city: "Woodstock", state: "VT", lat: 43.76, lon: -72.52, timezone: "America/New_York" },
  { name: "Ascutney", city: "Brownsville", state: "VT", lat: 43.42, lon: -72.45, timezone: "America/New_York" },
  { name: "Bellows Falls", city: "Bellows Falls", state: "VT", lat: 43.13, lon: -72.44, timezone: "America/New_York" },
  { name: "Bolton Valley", city: "Bolton Valley", state: "VT", lat: 44.4208, lon: -72.85, timezone: "America/New_York" },
  { name: "Brattleboro", city: "Brattleboro", state: "VT", lat: 42.85, lon: -72.56, timezone: "America/New_York" },
  { name: "Bromley", city: "Peru", state: "VT", lat: 43.2242, lon: -72.9389, timezone: "America/New_York" },
  { name: "Burke", city: "East Burke", state: "VT", lat: 44.5869, lon: -71.8989, timezone: "America/New_York" },
  { name: "Cochran's", city: "Richmond", state: "VT", lat: 44.38, lon: -72.9, timezone: "America/New_York" },
  { name: "Hard'Ack", city: "St. Albans", state: "VT", lat: 44.92, lon: -72.8, timezone: "America/New_York" },
  { name: "Harrington Hill", city: "Orleans", state: "VT", lat: 44.93, lon: -72.15, timezone: "America/New_York" },
  { name: "Hermitage Club", city: "Wilmington", state: "VT", lat: 42.96, lon: -72.86, timezone: "America/New_York" },
  { name: "Jay Peak", city: "Jay", state: "VT", lat: 44.9375, lon: -72.5053, timezone: "America/New_York" },
  { name: "Killington", city: "Killington", state: "VT", lat: 43.6222, lon: -72.7969, timezone: "America/New_York" },
  { name: "Lyndon Outing Club", city: "Lyndon", state: "VT", lat: 44.54, lon: -72.03, timezone: "America/New_York" },
  { name: "Mad River Glen", city: "Waitsfield", state: "VT", lat: 44.2025, lon: -72.9175, timezone: "America/New_York" },
  { name: "Magic Mountain", city: "Londonderry", state: "VT", lat: 43.1833, lon: -72.78, timezone: "America/New_York" },
  { name: "Middlebury Snowbowl", city: "Hancock", state: "VT", lat: 43.9428, lon: -72.9328, timezone: "America/New_York" },
  { name: "Mount Snow", city: "West Dover", state: "VT", lat: 42.96, lon: -72.9203, timezone: "America/New_York" },
  { name: "Northeast Slopes", city: "East Corinth", state: "VT", lat: 44.6, lon: -71.84, timezone: "America/New_York" },
  { name: "Okemo", city: "Ludlow", state: "VT", lat: 43.4011, lon: -72.7169, timezone: "America/New_York" },
  { name: "Pico", city: "Mendon", state: "VT", lat: 43.6614, lon: -72.8436, timezone: "America/New_York" },
  { name: "Quechee", city: "Quechee", state: "VT", lat: 43.65, lon: -72.43, timezone: "America/New_York" },
  { name: "Saskadena Six", city: "Pomfret", state: "VT", lat: 43.52, lon: -72.56, timezone: "America/New_York" },
  { name: "Smugglers' Notch", city: "Jeffersonville", state: "VT", lat: 44.5544, lon: -72.7892, timezone: "America/New_York" },
  { name: "Stowe", city: "Stowe", state: "VT", lat: 44.5308, lon: -72.7814, timezone: "America/New_York" },
  { name: "Stratton", city: "Stratton", state: "VT", lat: 43.1136, lon: -72.9083, timezone: "America/New_York" },
  { name: "Sugarbush", city: "Warren", state: "VT", lat: 44.1356, lon: -72.8986, timezone: "America/New_York" },
  { name: "Vermont State (Randolph)", city: "Randolph", state: "VT", lat: 43.93, lon: -72.67, timezone: "America/New_York" },
  { name: "Bryce", city: "Basye", state: "VA", lat: 38.835, lon: -78.7731, timezone: "America/New_York" },
  { name: "Homestead VA", city: "Hot Springs", state: "VA", lat: 37.9972, lon: -79.8908, timezone: "America/New_York" },
  { name: "Massanutten", city: "Massanutten", state: "VA", lat: 38.4103, lon: -78.7456, timezone: "America/New_York" },
  { name: "Wintergreen", city: "Wintergreen", state: "VA", lat: 37.9306, lon: -78.9386, timezone: "America/New_York" },
  { name: "49° North", city: "Chewelah", state: "WA", lat: 48.7933, lon: -117.5647, timezone: "America/Los_Angeles" },
  { name: "Badger Mountain", city: "Waterville", state: "WA", lat: 47.13, lon: -120.28, timezone: "America/Los_Angeles" },
  { name: "Bluewood", city: "Dayton", state: "WA", lat: 46.0819, lon: -117.8525, timezone: "America/Los_Angeles" },
  { name: "Crystal Mountain WA", city: "Enumclaw", state: "WA", lat: 46.9353, lon: -121.5042, timezone: "America/Los_Angeles" },
  { name: "Echo Valley", city: "Chelan", state: "WA", lat: 47.46, lon: -120.25, timezone: "America/Los_Angeles" },
  { name: "Hurricane Ridge", city: "Port Angeles", state: "WA", lat: 47.9697, lon: -123.4975, timezone: "America/Los_Angeles" },
  { name: "Leavenworth Ski Hill", city: "Leavenworth", state: "WA", lat: 47.59, lon: -120.67, timezone: "America/Los_Angeles" },
  { name: "Loup Loup", city: "Okanogan", state: "WA", lat: 48.3931, lon: -119.9117, timezone: "America/Los_Angeles" },
  { name: "Meany Lodge", city: "Easton", state: "WA", lat: 47.28, lon: -121.16, timezone: "America/Los_Angeles" },
  { name: "Mission Ridge", city: "Wenatchee", state: "WA", lat: 47.2922, lon: -120.4028, timezone: "America/Los_Angeles" },
  { name: "Mt. Baker", city: "Glacier", state: "WA", lat: 48.8575, lon: -121.6644, timezone: "America/Los_Angeles" },
  { name: "Mt. Spokane", city: "Spokane", state: "WA", lat: 47.9278, lon: -117.1028, timezone: "America/Los_Angeles" },
  { name: "Sahalie Ski Club", city: "Snoqualmie Pass", state: "WA", lat: 47.42, lon: -121.41, timezone: "America/Los_Angeles" },
  { name: "Snoqualmie: Alpental", city: "Snoqualmie Pass", state: "WA", lat: 47.4428, lon: -121.4267, timezone: "America/Los_Angeles" },
  { name: "Snoqualmie: Summit", city: "Snoqualmie Pass", state: "WA", lat: 47.4208, lon: -121.4139, timezone: "America/Los_Angeles" },
  { name: "Stevens Pass", city: "Skykomish", state: "WA", lat: 47.7453, lon: -121.0886, timezone: "America/Los_Angeles" },
  { name: "White Pass", city: "Packwood", state: "WA", lat: 46.6375, lon: -121.3906, timezone: "America/Los_Angeles" },
  { name: "Canaan Valley", city: "Davis", state: "WV", lat: 39.0039, lon: -79.4478, timezone: "America/New_York" },
  { name: "Oglebay", city: "Wheeling", state: "WV", lat: 40.07, lon: -80.64, timezone: "America/New_York" },
  { name: "Silver Creek (Snowshoe)", city: "Snowshoe", state: "WV", lat: 38.41, lon: -79.99, timezone: "America/New_York" },
  { name: "Snowshoe", city: "Snowshoe", state: "WV", lat: 38.4108, lon: -79.9942, timezone: "America/New_York" },
  { name: "Timberline WV", city: "Davis", state: "WV", lat: 39.0022, lon: -79.4211, timezone: "America/New_York" },
  { name: "Winterplace", city: "Flat Top", state: "WV", lat: 37.5878, lon: -81.0617, timezone: "America/New_York" },
  { name: "Alpine Valley WI", city: "East Troy", state: "WI", lat: 42.7153, lon: -88.54, timezone: "America/Chicago" },
  { name: "Ausblick Ski Club", city: "Sussex", state: "WI", lat: 43.14, lon: -88.18, timezone: "America/Chicago" },
  { name: "Blackhawk", city: "Middleton", state: "WI", lat: 43.42, lon: -89.75, timezone: "America/Chicago" },
  { name: "Bruce Mound", city: "Merrillan", state: "WI", lat: 44.39, lon: -90.68, timezone: "America/Chicago" },
  { name: "Camp 10", city: "Rhinelander", state: "WI", lat: 45.95, lon: -88.59, timezone: "America/Chicago" },
  { name: "Cascade", city: "Cascade", state: "WI", lat: 43.5753, lon: -87.9908, timezone: "America/Chicago" },
  { name: "Christie Mountain", city: "Bruce", state: "WI", lat: 45.1664, lon: -91.2392, timezone: "America/Chicago" },
  { name: "Christmas Mountain Village", city: "Wisconsin Dells", state: "WI", lat: 43.62, lon: -89.81, timezone: "America/Chicago" },
  { name: "Crystal Ridge", city: "Eau Claire", state: "WI", lat: 44.7, lon: -91.36, timezone: "America/Chicago" },
  { name: "Devil's Head", city: "Merrimac", state: "WI", lat: 43.4219, lon: -89.7469, timezone: "America/Chicago" },
  { name: "Fox Hill", city: "Mishicot", state: "WI", lat: 43.82, lon: -88.44, timezone: "America/Chicago" },
  { name: "Grand Geneva (Mountain Top)", city: "Lake Geneva", state: "WI", lat: 42.5994, lon: -88.4117, timezone: "America/Chicago" },
  { name: "Granite Peak", city: "Wausau", state: "WI", lat: 44.9319, lon: -89.6839, timezone: "America/Chicago" },
  { name: "Heiliger Huegel Ski Club", city: "Merrimac", state: "WI", lat: 43.3, lon: -89.74, timezone: "America/Chicago" },
  { name: "Kettlebowl", city: "Antigo", state: "WI", lat: 45.07, lon: -89.03, timezone: "America/Chicago" },
  { name: "Keyes Peak", city: "Florence", state: "WI", lat: 45.59, lon: -89.61, timezone: "America/Chicago" },
  { name: "Little Switzerland", city: "Slinger", state: "WI", lat: 43.2797, lon: -88.4206, timezone: "America/Chicago" },
  { name: "Mont du Lac", city: "Superior", state: "WI", lat: 46.65, lon: -92.21, timezone: "America/Chicago" },
  { name: "Mount Ashwabay", city: "Bayfield", state: "WI", lat: 46.7539, lon: -90.9242, timezone: "America/Chicago" },
  { name: "Mount La Crosse", city: "La Crosse", state: "WI", lat: 43.8314, lon: -91.2372, timezone: "America/Chicago" },
  { name: "Nordic Mountain", city: "Wild Rose", state: "WI", lat: 44.2606, lon: -89.2025, timezone: "America/Chicago" },
  { name: "Nutt Hill", city: "Lodi", state: "WI", lat: 43.74, lon: -89.75, timezone: "America/Chicago" },
  { name: "Paul Bunyan", city: "Lakewood", state: "WI", lat: 45.06, lon: -91.55, timezone: "America/Chicago" },
  { name: "Powers Bluff", city: "Arpin", state: "WI", lat: 44.58, lon: -90.06, timezone: "America/Chicago" },
  { name: "Standing Rocks Park", city: "Stevens Point", state: "WI", lat: 44.31, lon: -89.3, timezone: "America/Chicago" },
  { name: "Sunburst", city: "Kewaskum", state: "WI", lat: 43.3961, lon: -88.0656, timezone: "America/Chicago" },
  { name: "Sunset Hill (Forest Springs)", city: "Westfield", state: "WI", lat: 43.53, lon: -88.98, timezone: "America/Chicago" },
  { name: "Triangle Sports Area", city: "Chippewa Falls", state: "WI", lat: 44.95, lon: -90.24, timezone: "America/Chicago" },
  { name: "Trollhaugen", city: "Dresser", state: "WI", lat: 45.2972, lon: -92.6633, timezone: "America/Chicago" },
  { name: "Tyrol Basin", city: "Mount Horeb", state: "WI", lat: 43.1714, lon: -89.8344, timezone: "America/Chicago" },
  { name: "Whitecap Mountains", city: "Montreal", state: "WI", lat: 46.3686, lon: -90.1233, timezone: "America/Chicago" },
  { name: "Whitetail Ridge", city: "River Falls", state: "WI", lat: 42.45, lon: -90.29, timezone: "America/Chicago" },
  { name: "Wilmot", city: "Wilmot", state: "WI", lat: 42.5033, lon: -88.1881, timezone: "America/Chicago" },
  { name: "Winter Park (Kewaunee)", city: "Kewaunee", state: "WI", lat: 44.46, lon: -87.51, timezone: "America/Chicago" },
  { name: "Antelope Butte", city: "Shell", state: "WY", lat: 44.6206, lon: -107.4778, timezone: "America/Denver" },
  { name: "Beartooth Basin", city: "Cooke City", state: "WY", lat: 44.93, lon: -109.44, timezone: "America/Denver" },
  { name: "Grand Targhee", city: "Alta", state: "WY", lat: 43.7872, lon: -110.9578, timezone: "America/Denver" },
  { name: "Hogadon Basin", city: "Casper", state: "WY", lat: 42.7367, lon: -106.4008, timezone: "America/Denver" },
  { name: "Jackson Hole", city: "Teton Village", state: "WY", lat: 43.5875, lon: -110.8278, timezone: "America/Denver" },
  { name: "Meadowlark", city: "Ten Sleep", state: "WY", lat: 44.32, lon: -107.11, timezone: "America/Denver" },
  { name: "Pine Creek", city: "Cokeville", state: "WY", lat: 43.0619, lon: -110.7778, timezone: "America/Denver" },
  { name: "Snow King", city: "Jackson", state: "WY", lat: 43.4719, lon: -110.7617, timezone: "America/Denver" },
  { name: "Snowy Range", city: "Centennial", state: "WY", lat: 41.3406, lon: -106.1789, timezone: "America/Denver" },
  { name: "White Pine", city: "Pinedale", state: "WY", lat: 42.915, lon: -109.7617, timezone: "America/Denver" }
];

// Get unique states for grouping
export function getResortStates() {
  const states = [...new Set(SKI_RESORTS.map(r => r.state))];
  return states.sort();
}

// Filter resorts by search query
export function filterResorts(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return SKI_RESORTS.filter(r =>
    r.name.toLowerCase().includes(q) ||
    r.state.toLowerCase().includes(q) ||
    r.city.toLowerCase().includes(q)
  ).slice(0, 20); // Limit results
}

// Get resorts by state
export function getResortsByState(state) {
  return SKI_RESORTS.filter(r => r.state === state);
}
